import { Task, Meeting } from './types';

export const SEED_TASKS: Task[] = [
  {
    id: '1',
    title: 'Review Q3 Global Expansion Strategy',
    description: 'Deep dive into the operational plan for the Southeast Asia market entry. focus on logistics and local partnerships.',
    category: 'priority',
    priority: 'urgent',
    status: 'in-progress',
    dueDate: new Date().toISOString().split('T')[0],
    isRightNow: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Approve Series B Final Term Sheet',
    description: 'Final sign-off on the investment terms with Lead Venture Partners.',
    category: 'approval',
    priority: 'urgent',
    status: 'pending',
    owner: 'Legal Team',
    dueDate: new Date().toISOString().split('T')[0],
    isRightNow: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Executive Leadership Offsite',
    description: 'Prepare opening keynote for the annual strategy offsite in Bali.',
    category: 'priority',
    priority: 'high',
    status: 'pending',
    dueDate: new Date().toISOString().split('T')[0],
    isRightNow: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'AI Product Roadmap Audit',
    description: 'Technical audit of the new LLM integration layer for the core platform.',
    category: 'delegated',
    priority: 'medium',
    status: 'delegated',
    owner: 'CTO Office',
    dueDate: '2026-06-25',
    isRightNow: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Fix: Mobile App Latency Spike',
    description: 'Monitoring the implementation of the new CDN edge nodes to resolve EU latency issues.',
    category: 'alert',
    priority: 'urgent',
    status: 'delayed',
    dueDate: new Date().toISOString().split('T')[0],
    isRightNow: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Quarterly Board Presentation',
    description: 'Finalize financial slides and growth metrics for Monday morning board call.',
    category: 'deadline',
    priority: 'high',
    status: 'in-progress',
    dueDate: new Date().toISOString().split('T')[0],
    isRightNow: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_MEETINGS: Meeting[] = [
  {
    id: 'm1',
    title: 'Global Operations Sync',
    time: '10:00',
    person: 'Regional Directors',
    mode: 'online',
    status: 'completed',
  },
  {
    id: 'm2',
    title: 'Strategic Partnership Demo',
    time: '14:00',
    person: 'Microsoft Enterprise Team',
    mode: 'online',
    status: 'upcoming',
  },
  {
    id: 'm3',
    title: 'Private Equity Dinner',
    time: '20:00',
    person: 'Managing Partners',
    mode: 'in-person',
    status: 'upcoming',
  },
];
